### PR TITLE
ignore deleted and edited comments 

### PR DESCRIPTION
**Pull request by arqunis**
#3 (said yes to deleted ones too)

### CODE REVIEW

**Comment by meew0** [comment]
Why ignore? You could just change the message into something like `meew0 edited comment` or `meew0 deleted comment`.

**Comment by arqunis** [comment]
Well say that to gexo and others in d.js's channel but i can make it detect edited/deleted ones though _originally what i was planing for then realised the issue name_.

Unless rubot would be configuruble to accept or ignore webhooks and let them set what to ignore and such since this is the reason why i made the pull request anyways.

**Comment by meew0** [comment]
I don't see why one would ignore edits though, they're valuable information - it tells you that you should look at the comment again; maybe the edit was important.

**Comment by arqunis** [comment]
Guess i'm just gonna channge it to not ignore them.

**Comment by arqunis** [comment]
Welp, time passed by, we got webhooks, and figured this pr is useless now.

**Pull request closed without merging**
